CREATE TABLE IF NOT EXISTS `am_regions_block` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BLOCK_START_1` tinyint(3) UNSIGNED NOT NULL,
  `BLOCK_START_2` tinyint(3) UNSIGNED NOT NULL,
  `BLOCK_START_3` tinyint(3) UNSIGNED NOT NULL,
  `BLOCK_START_4` tinyint(3) UNSIGNED NOT NULL,
  `BLOCK_END_1` tinyint(3) UNSIGNED NOT NULL,
  `BLOCK_END_2` tinyint(3) UNSIGNED NOT NULL,
  `BLOCK_END_3` tinyint(3) UNSIGNED NOT NULL,
  `BLOCK_END_4` tinyint(3) UNSIGNED NOT NULL,
  `BLOCK_START` bigint(18) NOT NULL,
  `BLOCK_END` bigint(18) NOT NULL,
  `CITY_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_CITY_ID` (`CITY_ID`) USING BTREE,
  KEY `IX_BLOCK_START_1` (`BLOCK_START_1`),
  KEY `IX_BLOCK_START_2` (`BLOCK_START_2`),
  KEY `IX_BLOCK_START_3` (`BLOCK_START_3`),
  KEY `IX_BLOCK_START_4` (`BLOCK_START_4`),
  KEY `IX_BLOCK_END_1` (`BLOCK_END_1`),
  KEY `IX_BLOCK_END_2` (`BLOCK_END_2`),
  KEY `IX_BLOCK_END_3` (`BLOCK_END_3`),
  KEY `IX_BLOCK_END_4` (`BLOCK_END_4`),
  KEY `IX_BLOCK_START` (`BLOCK_START`),
  KEY `IX_BLOCK_END` (`BLOCK_END`)
);

CREATE TABLE IF NOT EXISTS `am_regions_city` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REGION_ID` int(11) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `LAT` double DEFAULT NULL,
  `LON` double DEFAULT NULL,
  `OKATO` varchar(20)  DEFAULT NULL,
  `LOCATION_ID` int(11) DEFAULT NULL,
  `IS_FAVORITE` char(1)  NOT NULL DEFAULT 'N',
  `IS_DEFAULT` char(1)  NOT NULL DEFAULT 'N',
  `EXT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_REGION_ID` (`REGION_ID`),
  KEY `IX_IS_FAVORITE` (`IS_FAVORITE`) USING BTREE,
  KEY `IX_IS_DEFAULT` (`IS_DEFAULT`) USING BTREE,
  KEY `IX_EXT_ID` (`EXT_ID`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `am_regions_city_lang` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CITY_ID` int(11) NOT NULL,
  `LID` char(2) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_CITYLID` (`CITY_ID`,`LID`),
  KEY `IX_LIDNAME` (`LID`,`NAME`)
);

CREATE TABLE IF NOT EXISTS `am_regions_content` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SITE_ID` CHAR(2) NULL DEFAULT NULL,
  `TYPE_ID` int(11) NOT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `REGION_ID` int(11) DEFAULT NULL,
  `CITY_ID` int(11) DEFAULT NULL,
  `DOMAIN_ID` int(11) DEFAULT NULL,
  `ACTIVE` char(1)  NOT NULL DEFAULT 'Y',
  `CONTENT` text,
  `CONTENT_LANG` LONGTEXT NULL DEFAULT NULL,
  `CONTENT_EXT` longtext ,
  PRIMARY KEY (`ID`),
  KEY `IX_TYPE_ID` (`TYPE_ID`),
  KEY `IX_COUNTRY_ID` (`COUNTRY_ID`),
  KEY `IX_REGION_ID` (`REGION_ID`),
  KEY `IX_CITY_ID` (`CITY_ID`),
  KEY `IX_ACTIVE` (`ACTIVE`) USING BTREE,
  KEY `IX_DOMAIN_ID` (`DOMAIN_ID`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `am_regions_content_types` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255)  NOT NULL,
  `IDENT` varchar(255)  NOT NULL,
  `CLASS` varchar(255)  NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `am_regions_country` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(2)  DEFAULT NULL,
  `CONTINENT` varchar(2) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `LAT` double DEFAULT NULL,
  `LON` double DEFAULT NULL,
  `TIMEZONE` varchar(100) DEFAULT NULL,
  `LOCATION_ID` int(11) DEFAULT NULL,
  `EXT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_EXT_ID` (`EXT_ID`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `am_regions_country_lang` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COUNTRY_ID` int(11) NOT NULL,
  `LID` char(2) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_COUNTRYLID` (`COUNTRY_ID`,`LID`),
  KEY `IX_LIDNAME` (`LID`,`NAME`)
);

CREATE TABLE IF NOT EXISTS `am_regions_domain` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255)  NOT NULL,
  `NAME_LANG` LONGTEXT NULL DEFAULT NULL,
  `ACTIVE` char(1)  NOT NULL DEFAULT 'Y',
  `IS_DEFAULT` char(1)  NOT NULL DEFAULT 'N',
  `DOMAIN` varchar(255)  NOT NULL,
  `PATHCODE` varchar(255)  NOT NULL,
  `ORDER_PREFIX` varchar(64) DEFAULT NULL,
  `SITE_ID` char(2)  NOT NULL,
  `SITE_EXT` text DEFAULT NULL,
  `CITY_ID` int(11) NOT NULL,
  `NOINDEX` char(1)  NOT NULL DEFAULT 'N',
  `SALE_UID` int(11) DEFAULT NULL,
  `SALE_COMPANY_ID` int(11) DEFAULT NULL,
  `DEFAULT_EMAIL` varchar(255)  NOT NULL,
  `VARIABLE_SEPARATOR` varchar(255)  NOT NULL DEFAULT ', ',
  `PRICES` longtext ,
  `STORES` longtext ,
  `COUNTERS` longtext ,
  `HEAD_STRING` longtext  NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_ACTIVE` (`ACTIVE`) USING BTREE,
  KEY `IX_PATHCODE` (`PATHCODE`) USING BTREE,
  KEY `IX_DOMAIN` (`DOMAIN`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `am_regions_domain_loc` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOMAIN_ID` int(11) NOT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `REGION_ID` int(11) DEFAULT NULL,
  `CITY_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `am_regions_domain_var` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOMAIN_ID` int(11) NOT NULL,
  `VARIABLE_ID` int(11) NOT NULL,
  `VALUE` longtext NULL DEFAULT NULL,
  `VALUE_LANG` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `am_regions_price` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACTIVE` char(1)  NOT NULL DEFAULT 'Y',
  `SORT` int(11) NOT NULL DEFAULT '100',
  `CURRENCY` char(3)  DEFAULT NULL,
  `PRICE_FROM_ID` int(11) NOT NULL,
  `PRICE_TO_ID` int(11) NOT NULL,
  `PRICE_CHANGE` char(2)  NOT NULL DEFAULT 'NC',
  `PRICE_CHANGE_VALUE` decimal(18,4) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `am_regions_region` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `CODE` varchar(10) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `OKATO` varchar(20) DEFAULT NULL,
  `TIMEZONE` varchar(100) DEFAULT NULL,
  `LOCATION_ID` int(11) DEFAULT NULL,
  `EXT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_COUNTRY_ID` (`COUNTRY_ID`),
  KEY `IX_EXT_ID` (`EXT_ID`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `am_regions_region_lang` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REGION_ID` int(11) NOT NULL,
  `LID` char(2) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_REGIONLID` (`REGION_ID`,`LID`),
  KEY `IX_LIDNAME` (`LID`,`NAME`)
);

CREATE TABLE IF NOT EXISTS `am_regions_variable` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` text,
  `CODE` varchar(255) NOT NULL,
  `IS_SYSTEM` char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UX_CODE` (`CODE`) USING BTREE
);
